=== ITHarbor/Aion-Germany-5.6/AL-Game/data/static_data/events_config/atreian_passports.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="atreian_passports">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="atreian_passport"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="atreian_passport">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="atreian_passport_reward"/>
			</xs:sequence>
			<xs:attribute name="active" use="required" type="xs:int"/>
			<xs:attribute name="attend_type" use="required" type="xs:string"/>
			<xs:attribute name="id" use="required" type="xs:int"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="atreian_passport_reward">
		<xs:complexType>
			<xs:attribute name="name" use="required"/>
			<xs:attribute name="reward_item" use="required" type="xs:int"/>
			<xs:attribute name="reward_item_count" use="required" type="xs:int"/>
			<xs:attribute name="reward_item_num" use="required" type="xs:int"/>
			<xs:attribute name="reward_permit_level" type="xs:int"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ITHarbor/Aion-Germany-5.6/AL-Game/data/static_data/events_config/atreian_passports.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- parsed by phpTools from Aion Germany Group (Mariella) at 2017-09-14 20:19 -->
<atreian_passports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="atreian_passports.xsd">
    <atreian_passport id="5" name="2016_attend_01_basic" active="1" attend_type="BASIC">
        <atreian_passport_reward reward_item_num="1" reward_item_count="1" reward_item="188055235" name="[Jakunerk] Noble Potion Bundle"/>
        <atreian_passport_reward reward_item_num="2" reward_item_count="1" reward_item="188055237" name="[Jakunerk] Noble Scroll Bundle"/>
        <atreian_passport_reward reward_item_num="3" reward_item_count="1" reward_item="188055236" name="[Jakunerk] Noble Serum Bundle"/>
        <atreian_passport_reward reward_item_num="4" reward_item_count="1" reward_item="188055238" name="[Jakunerk] Noble Bundle of Elemental Defence"/>
        <atreian_passport_reward reward_item_num="5" reward_item_count="1" reward_item="188055239" name="[Jakunerk] Bundle of 50 Mighty Socketing Aids"/>
        <atreian_passport_reward reward_item_num="6" reward_item_count="1" reward_item="188055244" name="[Jakunerk] Box with a Battle Medal"/>
        <atreian_passport_reward reward_item_num="7" reward_item_count="1" reward_item="162001064" name="[Jakunerk] Lodas' Golden Star (7 days)"/>
        <atreian_passport_reward reward_item_num="8" reward_item_count="1" reward_item="188055235" name="[Jakunerk] Noble Potion Bundle"/>
        <atreian_passport_reward reward_item_num="9" reward_item_count="1" reward_item="188055237" name="[Jakunerk] Noble Scroll Bundle"/>
        <atreian_passport_reward reward_item_num="10" reward_item_count="1" reward_item="188055236" name="[Jakunerk] Noble Serum Bundle"/>
        <atreian_passport_reward reward_item_num="11" reward_item_count="1" reward_item="188055238" name="[Jakunerk] Noble Bundle of Elemental Defence"/>
        <atreian_passport_reward reward_item_num="12" reward_item_count="1" reward_item="188055240" name="[Jakunerk] Bundle of 100 Mighty Socketing Aids"/>
        <atreian_passport_reward reward_item_num="13" reward_item_count="1" reward_item="188055246" name="[Jakunerk] Box: Insignia of Honour"/>
        <atreian_passport_reward reward_item_num="14" reward_item_count="1" reward_item="188055243" name="[Jakunerk] Noble Manastone Bundle"/>
        <atreian_passport_reward reward_item_num="15" reward_item_count="1" reward_item="188055235" name="[Jakunerk] Noble Potion Bundle"/>
        <atreian_passport_reward reward_item_num="16" reward_item_count="1" reward_item="188055237" name="[Jakunerk] Noble Scroll Bundle"/>
        <atreian_passport_reward reward_item_num="17" reward_item_count="1" reward_item="188055236" name="[Jakunerk] Noble Serum Bundle"/>
        <atreian_passport_reward reward_item_num="18" reward_item_count="1" reward_item="188055238" name="[Jakunerk] Noble Bundle of Elemental Defence"/>
        <atreian_passport_reward reward_item_num="19" reward_item_count="1" reward_item="188055241" name="[Jakunerk] Bundle of 150 Mighty Socketing Aids"/>
        <atreian_passport_reward reward_item_num="20" reward_item_count="1" reward_item="188055245" name="[Jakunerk] Noble Box of Battle Medals"/>
        <atreian_passport_reward reward_item_num="21" reward_item_count="1" reward_item="188055280" name="[Jakunerk] Augmentation Bundle"/>
        <atreian_passport_reward reward_item_num="22" reward_item_count="1" reward_item="188055235" name="[Jakunerk] Noble Potion Bundle"/>
        <atreian_passport_reward reward_item_num="23" reward_item_count="1" reward_item="188055237" name="[Jakunerk] Noble Scroll Bundle"/>
        <atreian_passport_reward reward_item_num="24" reward_item_count="1" reward_item="188055236" name="[Jakunerk] Noble Serum Bundle"/>
        <atreian_passport_reward reward_item_num="25" reward_item_count="1" reward_item="188055238" name="[Jakunerk] Noble Bundle of Elemental Defence"/>
        <atreian_passport_reward reward_item_num="26" reward_item_count="1" reward_item="188055242" name="[Jakunerk] Bundle of 200 Mighty Socketing Aids"/>
        <atreian_passport_reward reward_item_num="27" reward_item_count="1" reward_item="188055247" name="[Jakunerk] Noble Box of Insignias of Honour"/>
        <atreian_passport_reward reward_item_num="28" reward_item_count="1" reward_item="188055254" reward_permit_level="66" name="[Jakunerk] Mythical Armour Chest"/>
    </atreian_passport>
    <atreian_passport id="6" name="2016_attend_01_anniversary" active="1" attend_type="ANNIVERSARY">
        <atreian_passport_reward reward_item_num="1" reward_item_count="1" reward_item="188053423" reward_permit_level="66" name="[Stamp] Anniversary Chest"/>
    </atreian_passport>
</atreian_passports>
